/**
 * SDL Icon System — Maps emoji strings and icon names to Lucide components.
 *
 * Provides a consistent icon set across the entire UI while maintaining
 * backward compatibility with emoji-based `icon:` fields in SDL files.
 */

import {
  Telescope, Building2, Pin, BarChart3, Settings, GitBranch, Target,
  Dices, TrendingUp, TrendingDown, ClipboardList, Lightbulb, FileText,
  Globe, Users, Link2, Microscope, Sun, Coins, Baby, Wind, Hammer,
  Recycle, Cloud, Home, Camera, AlertTriangle, Zap, Eye, Bug, Droplets,
  UserRound, Shield, Car, Bot, Scale, Plug, Check, HardHat, Leaf, Pill,
  Banknote, CircuitBoard, Activity, Gauge, FlaskConical, Waves, Syringe,
  Smartphone, Rocket, Ban, Handshake, Skull, Timer, Flame, Factory,
  Wheat, Swords, UtensilsCrossed, Search, ArrowUp, ArrowDown, Heart,
  Laptop, Flag, Lock, SquareParking, Truck, CreditCard, Landmark, Dna,
  Sparkles, Diamond, CirclePlus, PenLine,
  type LucideIcon,
} from 'lucide-react';

const EMOJI_MAP: Record<string, LucideIcon> = {
  '🔭': Telescope,
  '🏗': Building2,
  '🏗️': Building2,
  '📌': Pin,
  '📊': BarChart3,
  '⚙': Settings,
  '⚙️': Settings,
  '🔀': GitBranch,
  '🎯': Target,
  '🎲': Dices,
  '📈': TrendingUp,
  '📉': TrendingDown,
  '📋': ClipboardList,
  '💡': Lightbulb,
  '📄': FileText,
  '🌍': Globe,
  '👥': Users,
  '🔗': Link2,
  '🔬': Microscope,
  '☀': Sun,
  '☀️': Sun,
  '🌞': Sun,
  '💰': Coins,
  '👶': Baby,
  '💨': Wind,
  '⛏': Hammer,
  '♻': Recycle,
  '♻️': Recycle,
  '☁': Cloud,
  '☁️': Cloud,
  '🏠': Home,
  '🏙': Building2,
  '📷': Camera,
  '📱': Smartphone,
  '⚠': AlertTriangle,
  '⚠️': AlertTriangle,
  '⚡': Zap,
  '👁': Eye,
  '👁️': Eye,
  '🦠': Bug,
  '💧': Droplets,
  '🧓': UserRound,
  '🛡': Shield,
  '🛡️': Shield,
  '🚗': Car,
  '🤖': Bot,
  '⚖': Scale,
  '⚖️': Scale,
  '🔌': Plug,
  '✓': Check,
  '✅': Check,
  '👷': HardHat,
  '🌿': Leaf,
  '💊': Pill,
  '💶': Banknote,
  '🧪': FlaskConical,
  '💉': Syringe,
  '🌊': Waves,
  '🚀': Rocket,
  '🚫': Ban,
  '🤝': Handshake,
  '☠': Skull,
  '⏱': Timer,
  '🔥': Flame,
  '🏭': Factory,
  '🌾': Wheat,
  '⚔': Swords,
  '🍽': UtensilsCrossed,
  '🔍': Search,
  '↑': ArrowUp,
  '↓': ArrowDown,
  '↗': TrendingUp,
  '❤': Heart,
  '⛓': Link2,
  '💻': Laptop,
  '🇺🇸': Flag,
  '🔒': Lock,
  '🇪🇺': Flag,
  '🅿': SquareParking,
  '🚛': Truck,
  '💳': CreditCard,
  '🏦': Landmark,
  '🧬': Dna,
  '✦': Sparkles,
  '◈': Diamond,
  '◆': Diamond,
  '⊕': CirclePlus,
};

const NAME_MAP: Record<string, LucideIcon> = {
  'telescope': Telescope,
  'building': Building2,
  'pin': Pin,
  'bar-chart': BarChart3,
  'settings': Settings,
  'git-branch': GitBranch,
  'target': Target,
  'dice': Dices,
  'trending-up': TrendingUp,
  'trending-down': TrendingDown,
  'clipboard-list': ClipboardList,
  'lightbulb': Lightbulb,
  'file-text': FileText,
  'globe': Globe,
  'users': Users,
  'link': Link2,
  'microscope': Microscope,
  'sun': Sun,
  'coins': Coins,
  'baby': Baby,
  'wind': Wind,
  'hammer': Hammer,
  'recycle': Recycle,
  'cloud': Cloud,
  'home': Home,
  'camera': Camera,
  'smartphone': Smartphone,
  'alert-triangle': AlertTriangle,
  'zap': Zap,
  'eye': Eye,
  'bug': Bug,
  'droplets': Droplets,
  'user': UserRound,
  'shield': Shield,
  'car': Car,
  'bot': Bot,
  'scale': Scale,
  'plug': Plug,
  'check': Check,
  'hard-hat': HardHat,
  'leaf': Leaf,
  'pill': Pill,
  'banknote': Banknote,
  'circuit-board': CircuitBoard,
  'activity': Activity,
  'gauge': Gauge,
  'flask': FlaskConical,
  'waves': Waves,
  'syringe': Syringe,
  'rocket': Rocket,
  'ban': Ban,
  'handshake': Handshake,
  'skull': Skull,
  'timer': Timer,
  'flame': Flame,
  'factory': Factory,
  'wheat': Wheat,
  'swords': Swords,
  'utensils': UtensilsCrossed,
  'search': Search,
  'arrow-up': ArrowUp,
  'arrow-down': ArrowDown,
  'heart': Heart,
  'laptop': Laptop,
  'flag': Flag,
  'lock': Lock,
  'square-parking': SquareParking,
  'truck': Truck,
  'credit-card': CreditCard,
  'landmark': Landmark,
  'dna': Dna,
  'sparkles': Sparkles,
  'diamond': Diamond,
  'circle-plus': CirclePlus,
  'pen-line': PenLine,
};

export function resolveIcon(icon: string): LucideIcon {
  return EMOJI_MAP[icon] ?? NAME_MAP[icon] ?? BarChart3;
}

interface SdlIconProps {
  name: string;
  size?: number;
  className?: string;
  strokeWidth?: number;
}

export function SdlIcon({ name, size = 16, className, strokeWidth = 1.5 }: SdlIconProps) {
  const Icon = resolveIcon(name);
  return <Icon size={size} className={className} strokeWidth={strokeWidth} />;
}
